routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Symfony\Component\Console\Input\Input;

Route::get('/', 'ConvocatoriaUsuarioController@index');


//RUTAS DE CONVOCATORIAS
Route::resource('convocatorias','ConvocatoriaController');
Route::get("/storage/convocatorias/{id}/{file}",function ($id,$file){
	return Storage::download("storage/convocatorias/$id/$file");
});
Route::get('convocatoria/{idConvocatoria}', 'ConvocatoriaController@show')->name('convocatorias.show');
Route::get('convocatoria/{idConvocatoria}/postulantes', 'ConvocatoriaController@calificacionesPostulante')->name('convocatorias.calificacionesPostulante');
Route::get('convocatoria/{idConvocatoria}/postulantes/{idUsuario}', 'ConvocatoriaUsuarioController@getNota')->name('convocatorias.getNota');
Route::get("/storage/convocatorias/{id}/reqGenerales/{file}",function ($id,$file){
	return Storage::download("storage/convocatorias/$id/reqGenerales/$file");
});
Route::get("/storage/convocatorias/{id}/reqIndispensables/{file}",function ($id,$file){
	return Storage::download("storage/convocatorias/$id/reqIndispensables/$file");
});


//RUTAS DE ROLES
Route::resource('roles','RoleController');

//RUTAS DE REQUISITOS
Route::resource('requisitos','RequisitoController');
Route::get("requisitos/add/{requisito}",'RequisitoController@agregar')->name('requisitos.agregar');

//RUTAS DE REQUERIMIENTOS
Route::resource('requerimientos','RequerimientoController');
Route::get("requerimientos/add/{requerimiento}",'RequerimientoController@agregar')->name('requerimientos.agregar');

//RUTAS DE SECCIONES
Route::resource('secciones','SeccionController');
Route::get("secciones/add/{seccion}",'SeccionController@agregar')->name('secciones.agregar');

//RUTAS DE SUBSECCIONES
Route::resource('subsecciones','SubSeccionController');
Route::get("subsecciones/add/{subseccion}",'SubSeccionController@agregar')->name('subsecciones.agregar');

//RUTAS DE ITEMS
Route::resource('items','ItemController');
Route::get("items/add/{item}",'ItemController@agregar')->name('items.agregar');

//Rutas de Login
Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login');
Route::post('logout', 'Auth\LoginController@logout')->name('logout');

// Rutas de Registro
Route::get('register', 'Auth\RegisterController@showRegistrationForm')->name('register');
Route::post('register', 'Auth\RegisterController@register');


//Rutas de Registro Receptor
Route::get('register/receptor', 'Auth\RegisterController@showRegistrationFormReceptor')->name('register');
Route::post('register/receptor', 'Auth\RegisterController@registerReceptor');


//Rutas de Registro Evaluador
Route::get('register/evaluador', 'Auth\RegisterController@showRegistrationFormEvaluador')->name('register');
Route::post('register/evaluador', 'Auth\RegisterController@registerEvaluador');

//Rutas de Recuperar Contraseña
Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
Route::post('password/reset', 'Auth\ResetPasswordController@reset');
 

//Rutas para postular  {

	//ruta para el poner el codigo
	Route::get("/postular/{idConvocatoria}",function ($idConvocatoria){
	return view('postulante.codigo')->with(compact('idConvocatoria'));
	})->name('postular.codigo');

	//ruta para mostrar los requerimientos indispensables
	Route::get("/postular/requerimientosIndispensables/{idConvocatoria}",'PostularController@getRequisitosIndispensables')->name('postular.getRequisitosIndispensables');

	//ruta para guardar los pdf de los requerimientos indispensables
	Route::post("/postular/requerimientosIndispensables/add/{idConvocatoria}",'PostularController@setRequisitosIndispensables')->name('postular.setRequisitosIndispensables');

	//ruta para guardar los pdf de los requerimientos generales
	Route::post("/postular/requerimientosGenerales/add/{idConvocatoria}/{contador}",'PostularController@addRequisitosGenerales')->name('postular.addRequisitosGenerales');

	//ruta para guardar los items
	Route::post("/postular/items/add/{idItem}/{contador}",'PostularController@addItems')->name('postular.addItems');

	//}

	//Ruta para receptor
	Route::get("/receptor/{idConvocatoria}",'RequisitoController@receptorShow')->name('receptor.show');

	Route::get("/receptor/evaluar/{idConvocatoria}/{idUser}",'RequisitoController@evaluar')->name('receptor.evaluar');
	Route::get("/receptor/evaluar/save/{idConvocatoria}/{idUser}",'RequisitoController@evaluarSave')->name('receptor.evaluarSave');

	Route::get("/receptor/evaluar/item/{idConvocatoria}/{idUser}/{contador}",'RequisitoController@evaluarItem')->name('receptor.evaluarItem');


	//rutas para evaluador
	Route::get("/evaluador/{idConvocatoria}",'RequerimientoController@requerimientosShow')->name('evaluador.show');

	Route::get("/evaluador/show/{idConvocatoria}/{idUser}",'RequerimientoController@showItems')->name('evaluador.showItems');

	Route::get("/evaluador/save/{idItem}/{idUsuario}",'RequerimientoController@save')->name('evaluador.save');
	Route::get("/evaluador/show/{idConvocatoria}/{idUser}/{contador}",'RequerimientoController@siguiente')->name('evaluador.siguiente');



Route::resource('postular','PostularController');

//

Route::get("/receptor/convocatorias",'ConvocatoriaController@receptor');


Route::get('/home', 'HomeController@index');


Route::get("/postular/{codigo}",function ($codigo){
	return view('convocatorias.formRequerimientos')->with(compact('requerimiento'));;
});

app/convocatoria.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class convocatoria extends Model
{

    public function archivos(){
        return $this->morphMany('App\Archivo','archivoTable');
    }
    public function comisionCalificadoras(){
        return $this->hasMany('App\ComisionCalificadora');
    }
    public function usuarios(){
        return $this->belongsToMany('App\usuario');
    }

}

app/Http/Controllers/ConvocatoriaController.php
<?php

namespace App\Http\Controllers;

use App\convocatoria;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\View;

class ConvocatoriaController extends Controller
{
    public function index()
    {
        $convocatorias=convocatoria::paginate(10);
        return view('convocatorias.index')->with(compact('convocatorias'));

    }

    public function create()
    {
        return view('convocatorias.form');
    }

    public function store(Request $request)
    {          
        $datosConvocatoria=request()->except("_token");
    
        $data=new convocatoria;
        $data->titulo = $datosConvocatoria['Titulo'];
        $data->area = $datosConvocatoria['area'];
        $data->descripcion = $datosConvocatoria['descripcion'];
        $data->fechaIni = $datosConvocatoria['fechaIni'];
        $data->fechaFin = $datosConvocatoria['fechaFin'];
        $data->fechaIniBole = $datosConvocatoria['fechaIniBole'];
        $data->fechaFinBole = $datosConvocatoria['fechaFinBole'];
        $data->fechaLimRequisitos=$datosConvocatoria['fechaFinBole'];
        $data->codigo=substr(uniqid(rand(), true),5, 5);
        $data->save();
        $id=$data->id;
        

        $imagen=$request->file("imagen");
        $sub_path="storage/convocatorias/$id";
        $destino_path=public_path($sub_path);
        if (!file_exists($destino_path)) {
                mkdir($destino_path, 0777, true);
                }
        if(isset($imagen)){
            //$real_name=$imagen->getClientOriginalName();
            
            $tamanio = $imagen->getSize();
            $extension = $imagen->getClientOriginalExtension();
            $imagen->move($destino_path,"imagen".".$extension");
        }
        
        $pdf=$request->file("pdf");
        if(isset($pdf)){
            //$real_name=$pdf->getClientOriginalName();
            $tamanio = $pdf->getSize();
            $pdf->move($destino_path,"documento.pdf");
        }
        


        
        return redirect(route('requisitos.show', $id)); 

    }
    public function show($idConvocatoria,Request $request)
    {
        $convocatoria=\App\convocatoria::find($idConvocatoria);  
        $requisitosIndispensables=\DB::select("SELECT requisitos.* from convocatorias, requisitos where requisitos.convocatoria_id=? and requisitos.indispensable=1 AND convocatorias.id=requisitos.convocatoria_id",[$idConvocatoria]);
        $requisitosGenerales=\DB::select("SELECT requisitos.* from convocatorias, requisitos where requisitos.convocatoria_id=? and requisitos.indispensable=0 and convocatorias.id=requisitos.convocatoria_id",[$idConvocatoria]);
        $secciones=\DB::select('SELECT seccions.* , convocatorias.titulo as convocatoriaTitulo FROM convocatorias,seccions, requerimientos WHERE convocatorias.id=requerimientos.convocatoria_id and seccions.requerimiento_id=requerimientos.id AND requerimientos.convocatoria_id=?  ORDER BY seccions.id',[$idConvocatoria]);
        
        return view('convocatorias.convocatorias')->with(compact('convocatoria','requisitosIndispensables','requisitosGenerales','secciones'));
    }

    public function edit(convocatoria $convocatoria)
    {
        //
    }

    public function update(Request $request, convocatoria $convocatoria)
    {
        //
    }


    public function destroy($id)
    {
        $convocatoria=convocatoria::find($id);
        $convocatoria->delete();
        $sub_path="storage/convocatorias/$id";
        $destino_path=public_path($sub_path);
        foreach(glob($destino_path . "/*") as $archivos_carpeta){             
        if (is_dir($archivos_carpeta)){
          rmDir_rf($archivos_carpeta);
        } else {
        unlink($archivos_carpeta);
        }
      }
      rmdir($destino_path);
     
        return redirect('convocatorias');
    }

    public function receptor(){
        $convocatorias=convocatoria::all();
        return view('convocatorias.receptor')->with(compact('convocatorias'));

    }
    
    public function calificacionesPostulante($idConvocatoria){
        $convocatoria=\App\convocatoria::find($idConvocatoria); 
        $notas=\DB::select('SELECT nota_requerimientos.*, users.name, users.email,users.id
        FROM nota_requerimientos,users,requerimientos,convocatorias
        WHERE convocatorias.id=requerimientos.convocatoria_id
        AND nota_requerimientos.Requerimiento_id=requerimientos.id 
        AND nota_requerimientos.user_id=users.id
        and nota_requerimientos.evaluado=1
        AND nota_requerimientos.Requerimiento_id=?'
         ,[$idConvocatoria,]);        
         $notaReq=\DB::select('SELECT requerimientos.MaximaNota
        FROM requerimientos,convocatorias
        WHERE convocatorias.id=requerimientos.convocatoria_id
        AND requerimientos.convocatoria_id=?', [$idConvocatoria]);
        return view('postulante.calificaciones')->with(compact('notas','convocatoria','idConvocatoria','notaReq'));
    }
}

resources/views/convocatorias/evaluador.blade.php
@extends('layout.principal')

@section('content')
<link href="{{asset('css/style_eval.css')}}" rel="Stylesheet">
<div class="container">
    <h1 class="page-header text-center"><strong>CONVOCATORIAS<strong></h1>
    <div class="row">
        @foreach ($convocatorias as $convocatoria)
        <div class="col-sm" style="margin-top:5px">
            
            <div class="card container select" style="width: 18rem;">
                <a href="#">
                <img src="{{ asset(('storage/convocatorias').'/'.$convocatoria->id.'/'.'imagen.jpg') }}" class="card-img-top" alt="img" onerror="this.onerror=null;this.src='{{asset('img/logo-convocatoria.jpg')}}';">
                <div class="card-body">
                    <h5 class="card-title font-weight-bold text-center txt">{{$convocatoria->titulo}}</h5>
                    <p class="card-text font-weight-bold text-center">{{$convocatoria->descripcion}}</p>
                </div>
                </a>
            </div>
            
        </div>
        @endforeach
    </div>
</div>

@stop

resources/views/convocatorias/formRequisitos.blade.php
@extends('layout.principal')
@section('body-class','profile-page sidebar-collapse')
@section('content')

<div class="page-header header-filter" data-parallax="true" style="background-image: url('../img/imagen4.jpg')">
</div>
  <div class="main main-raised">
    <div class="container">  
      <div class="section"> 
    <div class="container" style="margin-top: 15px">
    <h2 class="text-center">REQUISITOS</h2>
    <table class="table table-light table-hover">
        <thead class="thead-light">
            <tr>
                <th>Tipo de requisito</th>
                <th>Titulo</th>
                <th>Descripcion</th>
            </tr>
        </thead>
        <tbody style="font-weight: bold">
        <label style="display:none">
        {{$requisitos=\App\Requisito::where("convocatoria_id","$requisito")->get()}}
        </label>
        @foreach($requisitos as $re)
            <tr>
                <td>
                  <?php
                    if(($re->indispensable)==true)
                      echo "Indispensable";
                    else
                      echo "General";
                  ?>
                </td>
                <td>{{$re->nombre}}</td>
                <td>{{$re->descripcion}}</td>
                <td>
                    <form action="{{route('requisitos.destroy', $re->id)}}" method="post" style="display:inline">
                    {{csrf_field()}}
                    {{ method_field('DELETE')}}
                    <button class="btn btn-danger" type="submit" onclick="return confirm('¿Estas seguro de borrar esta convocatoria?')">Borrar</button>
                    </form>
                  </td>
            </tr>
        @endforeach
        </tbody>
    </table>
<br>
<br>
<form action="{{route('requisitos.agregar', $requisito)}}" method="get" class="needs-validation" novalidate id="myForm" enctype="multipart/form-data">
    {{ csrf_field() }}
    <div class="form-group col-md-4">
          <label for="fechaFin">{{'Fecha Inicial entrega de requisitos'}}</label>
          <input type="date" name="fechaFin" class="form-control" id="fechaFin" value="<?php echo date('Y-m-d',strtotime(\App\convocatoria::find($requisito)->fechaLimRequisitos))?>" placeholder="09/10/2019" required>
          <div class="invalid-feedback">
            Fecha invalida
          </div>
    </div>
    <br>
<hr style="border-top: 3px double #8c8b8b">
<br>
    <h2>¿Desea agregar nuevos requisitos?</h2>
    <div class="form-group col-md-6">
          <label for="Titulo">{{'Titulo del requisito'}}</label>
          <input type="text" name="Titulo" class="form-control" id="Titulo" required>
          <div class="invalid-feedback">
            Debe llenar el campo
          </div>
    </div>
        
    <div class="form-group">
        <label for="Descripcion">{{'Descripcion'}}</label>
        <textarea class="form-control" name="descripcion" id="descripcion" rows="3" required></textarea>
        <div class="invalid-feedback">
            Debe llenar el campo
        </div>
    </div>
    <div class="checkbox">
        <label>
          <input type="checkbox" name="Indispensable" id="Indispensable" value="1">
          Indispensable
    </label>

      </div>
    <button type="submit" class="btn btn-success">Agregar requisito</button>
</form>

<br><br>

<form action="{{route('requerimientos.show', $requisito)}}" method="get" style="display:inline">
<button type="submit" class="btn btn-primary btn-lg btn-block">Siguiente</button>
</form>
  
    <script>
        // Example starter JavaScript for disabling form submissions if there are invalid fields
        (function() {
          'use strict';
          window.addEventListener('load', function() {
            // Fetch all the forms we want to apply custom Bootstrap validation styles to
            var forms = document.getElementsByClassName('needs-validation');
            // Loop over them and prevent submission
            var validation = Array.prototype.filter.call(forms, function(form) {
              form.addEventListener('submit', function(event) {
                if (form.checkValidity() === false) {
                  event.preventDefault();
                  event.stopPropagation();
                }
                form.classList.add('was-validated');
              }, false);
            });
          }, false);
        })();
    </script>
    
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

         
      </div>
    </div>
  </div>
<footer class="footer">
      <div class="container">
        <nav class="float-left">
          <ul>
            <li>
              <a href="">
                SISCONV
              </a>
            </li>
            <li>
              <a href="">
                Acerca de nosotros
              </a>
            </li>
            <li>
              <a href="">
                Blog
              </a>
            </li>
          </ul>
        </nav>
        <div class="copyright float-right">
          &copy;
          <script>
            document.write(new Date().getFullYear())
          </script>Sisconv <i class="material-icons"> laptop </i> <i class="material-icons"> smartphone </i>Sistema de Convocatorias
        </div>
      </div>
  </footer>


  

resources/views/convocatorias/formSecciones.blade.php
@extends('layout.principal')
@section('body-class','profile-page sidebar-collapse')
@section('content')

<div class="page-header header-filter" data-parallax="true" style="background-image: url('../img/imagen4.jpg')">
</div>
  <div class="main main-raised">
    <div class="container">  
      <div class="section"> 
    <div class="container" style="margin-top: 15px">
    <h2 class="text-center">SECCIONES</h2>
    <table class="table table-light table-hover">
    <thead class="thead-light">
        <tr>
            <th>Titulo</th>
            <th>Nota Maxima</th>
            <!-- <th>Punto Numero</th> -->

        </tr>
    </thead>
    <tbody style="font-weight: bold">
    <label style="display:none">
    {{$secciones=\App\Seccion::where("requerimiento_id","$seccion")->get()}}
    </label>
    @foreach($secciones as $se)
        <tr>
            <td>{{$se->titulo}}</td>
            <td>{{$se->NotaMaxima}}</td>
            <!-- <td>{{$se->puntoNumero}}</td> -->
            <td>
                <form action="{{route('secciones.destroy', $se->id)}}" method="post" style="display:inline">
                {{csrf_field()}}
                {{ method_field('DELETE')}}
                <button class="btn btn-danger" type="submit" onclick="return confirm('¿Estas seguro de borrar esta seccion?')">Borrar</button>
                </form>
              </td>
        </tr>
    @endforeach
    </tbody>
</table>
<br>
<br>

<form action="{{route('secciones.agregar', $seccion)}}" method="get" class="needs-validation" novalidate id="myForm" enctype="multipart/form-data">
    {{ csrf_field() }}
    
    <br>
<hr style="border-top: 3px double #8c8b8b">
<br>
    <h2>¿Desea agregar nuevas secciones?</h2>
    <div class="form-group col-md-6">
          <label for="Titulo">{{'Titulo'}}</label>
          <input type="text" name="Titulo" class="form-control" id="Titulo" required>
          <div class="invalid-feedback">
            Debe llenar el campo
          </div>
    </div>
        
    <div class="form-group">
        <label for="NotaMaxima">{{'Nota Maxima'}}</label>
        <input type="text" class="form-control" name="NotaMaxima" id="NotaMaxima" rows="3" required pattern="[0-9]+">
        <div class="invalid-feedback">
            Debe llenar el campo
        </div>
    </div>
    <button type="submit" class="btn btn-success">Agregar Seccion</button>
</form>


<br><br>

<form action="{{route('subsecciones.show', $seccion)}}" method="get" style="display:inline">
<button type="submit" class="btn btn-primary btn-lg btn-block">Siguiente</button>
</form>
  
    <script>
        // Example starter JavaScript for disabling form submissions if there are invalid fields
        (function() {
          'use strict';
          window.addEventListener('load', function() {
            // Fetch all the forms we want to apply custom Bootstrap validation styles to
            var forms = document.getElementsByClassName('needs-validation');
            // Loop over them and prevent submission
            var validation = Array.prototype.filter.call(forms, function(form) {
              form.addEventListener('submit', function(event) {
                if (form.checkValidity() === false) {
                  event.preventDefault();
                  event.stopPropagation();
                }
                form.classList.add('was-validated');
              }, false);
            });
          }, false);
        })();
    </script>
    
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

         
      </div>
    </div>
  </div>
<footer class="footer">
      <div class="container">
        <nav class="float-left">
          <ul>
            <li>
              <a href="">
                SISCONV
              </a>
            </li>
            <li>
              <a href="">
                Acerca de nosotros
              </a>
            </li>
            <li>
              <a href="">
                Blog
              </a>
            </li>
          </ul>
        </nav>
        <div class="copyright float-right">
          &copy;
          <script>
            document.write(new Date().getFullYear())
          </script>Sisconv <i class="material-icons"> laptop </i> <i class="material-icons"> smartphone </i>Sistema de Convocatorias
        </div>
      </div>
  </footer>


  

resources/views/convocatorias/formSubsecciones.blade.php
@extends('layout.principal')
@section('body-class','profile-page sidebar-collapse')
@section('content')

<div class="page-header header-filter" data-parallax="true" 
style="background-image: url( {{ asset('../img/imagen4.jpg') }} );">>

</div>
  <div class="main main-raised">
    <div class="container">  
      <div class="section"> 
    <div class="container" style="margin-top: 15px">
    <h2 class="text-center">SUBSECCIONES</h2>
    <table class="table table-light table-hover">
    <thead class="thead-light">
        <tr>
            <th>Titulo</th>
            <!-- <th>Descripcion</th>
            <th>Punto numero</th> -->
            <th>Seccion</th>
        </tr>
    </thead>
    <tbody style="font-weight: bold">
    <label style="display:none">


      
      {{$secciones=\App\Seccion::where("requerimiento_id",$id)->get()}}

    </label>
    @foreach($subsecciones as $re) 

        
        <tr>
            <td>{{$re->titulo}}</td>
            <!-- <td>{{$re->descripcion}}</td>
            <td>{{$re->puntoNumero}}</td> -->
            <td>{{$re->titulo_seccion}}</td>
            <td>
            <form action="{{route('subsecciones.destroy',$re->id)}}" method="post" style="display:inline">
                {{csrf_field()}}
                {{ method_field('DELETE')}}
                <button class="btn btn-danger" type="submit" onclick="return confirm('¿Estas seguro de borrar esta convocatoria?')">Borrar</button>
                </form>
              </td>
        </tr>
    @endforeach
    </tbody>
     
</table>
<br>
<br>

<form action="{{route('subsecciones.agregar',$id)}}" method="get" class="needs-validation" novalidate id="myForm" enctype="multipart/form-data">
    {{ csrf_field() }}
    
    <br>
<hr style="border-top: 3px double #8c8b8b">
<br>
    <h2>¿Desea agregar nuevas subsecciones?</h2>
    <div class="form-group col-md-6">
          <label for="Titulo">{{'Titulo'}}</label>
          <input type="text" name="Titulo" class="form-control" id="Titulo" required>
          <div class="invalid-feedback">
            Debe llenar el campo
          </div>
    </div>
    <div class="form-group col-md-5">
          <label for="Seccion">{{'Seccion'}}</label>
            <select class="form-control" name="Seccion" id="Seccion">
              <option value="0">Sin seleccionar</option>
              @foreach ($secciones as $seccion)
              <option value="{{ $seccion->id }}">{{ $seccion->titulo}}</option>
              @endforeach
            </select>
          </div>
    <!-- <div class="form-group">
        <label for="Descripcion">{{'Descripcion'}}</label>
        <textarea class="form-control" name="descripcion" id="descripcion" rows="3" required></textarea>
        <div class="invalid-feedback">
            Debe llenar el campo
        </div>
    </div> -->

    <button type="submit" class="btn btn-success">Agregar sub Seccion</button>
</form>

<br><br>

<form action="{{route('items.show', $id)}}" method="get" style="display:inline">
<button type="submit" class="btn btn-primary btn-lg btn-block">Siguiente</button>
</form>

  
    <script>
        // Example starter JavaScript for disabling form submissions if there are invalid fields
        (function() {
          'use strict';
          window.addEventListener('load', function() {
            // Fetch all the forms we want to apply custom Bootstrap validation styles to
            var forms = document.getElementsByClassName('needs-validation');
            // Loop over them and prevent submission
            var validation = Array.prototype.filter.call(forms, function(form) {
              form.addEventListener('submit', function(event) {
                if (form.checkValidity() === false) {
                  event.preventDefault();
                  event.stopPropagation();
                }
                form.classList.add('was-validated');
              }, false);
            });
          }, false);
        })();
    </script>
    
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

         
      </div>
    </div>
  </div>
<footer class="footer">
      <div class="container">
        <nav class="float-left">
          <ul>
            <li>
              <a href="">
                SISCONV
              </a>
            </li>
            <li>
              <a href="">
                Acerca de nosotros
              </a>
            </li>
            <li>
              <a href="">
                Blog
              </a>
            </li>
          </ul>
        </nav>
        <div class="copyright float-right">
          &copy;
          <script>
            document.write(new Date().getFullYear())
          </script>Sisconv <i class="material-icons"> laptop </i> <i class="material-icons"> smartphone </i>Sistema de Convocatorias
        </div>
      </div>
  </footer>


  